[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "podo"
version = "0.1.0"
description = "A simple CLI to-do app"
requires-python = ">=3.10"
dependencies = [
	"typer>=0.27.2",
]

[project.scripts]
podo = "main:app"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["main", "task", "task_manager"]
